
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '783AF57742E01F6DBFFD819CBB4EDAF9'
    
_lr_action_items = {'SHOOT':([0,4,7,9,17,18,20,26,28,],[1,-8,-5,1,-6,-7,-4,1,1,]),'ENEMY':([10,],[22,]),'NEWLINE':([0,3,4,6,7,8,9,11,12,13,14,15,16,17,18,19,20,21,23,26,28,29,31,32,],[4,-12,-8,17,-5,18,4,-10,-14,-16,-15,-13,-9,-6,-7,25,-4,18,26,4,4,-17,-11,-18,]),'END':([0,4,7,9,17,18,20,26,28,],[3,-8,-5,19,-6,-7,-4,3,3,]),'WEST':([1,2,27,30,],[13,13,13,13,]),'IS':([22,24,],[-19,27,]),'MOVE':([0,4,7,9,17,18,20,26,28,],[2,-8,-5,2,-6,-7,-4,2,2,]),'error':([0,4,7,9,17,18,20,26,28,],[8,-8,-5,21,-6,-7,-4,21,21,]),'NOT':([27,],[30,]),'NORTH':([1,2,27,30,],[12,12,12,12,]),'ENDIF':([4,7,17,18,20,28,],[-8,-5,-6,-7,-4,31,]),'EAST':([1,2,27,30,],[14,14,14,14,]),'$end':([5,8,19,25,],[0,-3,-1,-2,]),'SOUTH':([1,2,27,30,],[15,15,15,15,]),'IF':([0,4,7,9,17,18,20,26,28,],[10,-8,-5,10,-6,-7,-4,10,10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'direction':([1,2,27,30,],[11,16,29,32,]),'relexpr':([10,],[23,]),'statements':([0,26,],[9,28,]),'object':([10,],[24,]),'program':([0,],[5,]),'command':([0,9,26,28,],[6,6,6,6,]),'statement':([0,9,26,28,],[7,20,7,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements END','program',2,'p_program','roboparse.py',9),
  ('program -> statements END NEWLINE','program',3,'p_program','roboparse.py',10),
  ('program -> error','program',1,'p_program_error','roboparse.py',19),
  ('statements -> statements statement','statements',2,'p_statements','roboparse.py',24),
  ('statements -> statement','statements',1,'p_statements','roboparse.py',25),
  ('statement -> command NEWLINE','statement',2,'p_statement','roboparse.py',39),
  ('statement -> error NEWLINE','statement',2,'p_statement_bad','roboparse.py',49),
  ('statement -> NEWLINE','statement',1,'p_statement_newline','roboparse.py',57),
  ('command -> MOVE direction','command',2,'p_command_move','roboparse.py',63),
  ('command -> SHOOT direction','command',2,'p_command_shoot','roboparse.py',67),
  ('command -> IF relexpr NEWLINE statements ENDIF','command',5,'p_command_if','roboparse.py',71),
  ('command -> END','command',1,'p_command_end','roboparse.py',76),
  ('direction -> SOUTH','direction',1,'p_dir_south','roboparse.py',81),
  ('direction -> NORTH','direction',1,'p_dir_north','roboparse.py',85),
  ('direction -> EAST','direction',1,'p_dir_east','roboparse.py',89),
  ('direction -> WEST','direction',1,'p_dir_west','roboparse.py',93),
  ('relexpr -> object IS direction','relexpr',3,'p_relexpr_dir','roboparse.py',99),
  ('relexpr -> object IS NOT direction','relexpr',4,'p_relexpr_dir_neg','roboparse.py',104),
  ('object -> ENEMY','object',1,'p_object','roboparse.py',108),
]
